apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yair232/status-page  # Replace with your actual Git repo URL
    targetRevision: dev
    path: k8s  # Path to the root directory containing both app and monitoring-stack folders
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Target namespace for the application deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true  # Automatically create namespaces if needed
