apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-monitor
  labels:
    app: prometheus
    release: prometheus  # Adding the release label
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
    - port: redis-exporter
      path: /metrics
      interval: 30s
