apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: system-alerts
  namespace: monitoring
spec:
  groups:
    - name: system-alerts
      rules:
        - alert: HighCPUUsage
          expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (instance) > 0.9
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage on {{ $labels.instance }}"
            description: "CPU usage is above 90% for more than 5 minutes."

        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High Memory Usage on {{ $labels.instance }}"
            description: "Memory usage is above 90% for more than 5 minutes."
