pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS_ID = 'github-ssh-key'  // SSH key credential ID for GitHub
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    echo "Cloning the Git repository..."
                }
                git branch: 'main',
                    url: 'git@github.com:yair232/status-page.git',
                    credentialsId: "${GITHUB_CREDENTIALS_ID}"
            }
        }

        stage('Set Permissions') {
            steps {
                script {
                    echo "Setting executable permissions..."
                }
                sh '''
                chmod +x statuspage/manage.py
                chmod +x upgrade.sh
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    echo "Installing dependencies..."
                }
                sh '''
                # Ensure Python and pip are installed
                python3 --version || sudo apt-get install python3
                pip3 --version || sudo apt-get install python3-pip
                
                # Install pytest
                pip3 install pytest
                '''
            }
        }

        stage('Run Unit Tests') {
            steps {
                script {
                    echo "Running unit tests using pytest..."
                }
                // Run the unit tests directly without changing directories
                sh '''
                pytest unitest.py
                '''
            }
        }
    }

    post {
        always {
            script {
                echo "Cleaning up workspace..."
            }
            cleanWs()
        }
    }
}
