apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-app
  namespace: argocd
spec:
  destination:
    namespace: elastic-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yair232/status-page.git
    path: k8s/logging
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - "ServerSideApply=true"
    automated:
      prune: true
      selfHeal: true
  syncWave: '7'
