apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yair232/status-page.git
    path: k8s/namespace
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - "ServerSideApply=true"
    automated:
      prune: true
      selfHeal: true
  syncWave: '0'
  hooks:
   - type: PostSync
     command: ["sh", "-c", "echo 'Waiting 10 seconds before proceeding...'; sleep 10"]
