global:
  evaluation_interval: 15s
  scrape_interval: 15s

kube-prometheus-stack:
  alertmanager:
    enabled: true
    alertmanagerSpec:
      config:
        global:
          smtp_smarthost: 'smtp.gmail.com:587'
          smtp_from: 'y.rproject123@gmail.com'
          smtp_auth_username: 'y.rproject123@gmail.com'
          smtp_auth_password: 'RY123456789'
          smtp_require_tls: true
        receivers:
          - name: 'email-notifications'
            email_configs:
              - to: 
                  - 'yair.ginat@nitzanim.tech'
                  - 'ron.tzidky@nitzanim.tech'
  grafana:
    admin:
      existingSecret: grafana
      adminPasswordKey: admin.password
    dashboardsConfigMaps:
      default: grafana-dashboard
    sidecar:
      dashboards:
        enabled: true
        folder: /var/lib/grafana/dashboards
        label: grafana-dashboard
