pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'  // Set your AWS region
        GITHUB_TOKEN = credentials('github-pat')  // GitHub PAT stored in Jenkins credentials
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone the repository using the GitHub PAT
                git credentialsId: 'github-pat', url: 'https://github.com/yair232/status-page.git', branch: 'main'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('final-project-terraform') {
                    // Initialize Terraform
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('final-project-terraform') {
                    // Run Terraform plan to see the changes
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Approval') {
            input {
                message "Do you want to apply these changes?"
                ok "Apply"
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('final-project-terraform') {
                    // Apply the changes if approved
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }

    post {
        always {
            cleanWs()  // Clean up workspace
        }
        success {
            echo 'Terraform pipeline executed successfully!'
        }
        failure {
            echo 'Terraform pipeline failed!'
        }
    }
}
