pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'  // AWS Region
        TF_VAR_db_password = credentials('rds-db-password')  // RDS password from Jenkins credentials
        TF_VAR_status_page_password = credentials('status-page-password')  // Status page user password
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the Terraform code from GitHub
                git 'https://github.com/yair232/status-page.git'
            }
        }

        stage('Terraform Init') {
            steps {
                // Initialize Terraform
                dir('final-project-terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                // Run Terraform Plan to preview changes
                dir('final-project-terraform') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                // Apply the Terraform configuration to create infrastructure
                dir('final-project-terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Run SQL Commands') {
            steps {
                script {
                    // SSH into the EC2 instance and run PostgreSQL commands
                    sshagent(['ec2-ssh-key']) {
                        sh '''
                            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_INSTANCE_IP} << EOF
                            export PGPASSWORD="${TF_VAR_db_password}"
                            psql -h ${RDS_ENDPOINT} -U ${DB_USERNAME} -d ${DB_NAME} -c "CREATE DATABASE \\"status-page\\";"
                            psql -h ${RDS_ENDPOINT} -U ${DB_USERNAME} -d ${DB_NAME} -c "CREATE USER \\"status-page\\" WITH PASSWORD '${TF_VAR_status_page_password}';"
                            psql -h ${RDS_ENDPOINT} -U ${DB_USERNAME} -d ${DB_NAME} -c "ALTER DATABASE \\"status-page\\" OWNER TO \\"status-page\\";"
                            psql -h ${RDS_ENDPOINT} -U ${DB_USERNAME} -d ${DB_NAME} -c "GRANT CREATE ON SCHEMA public TO \\"status-page\\";"
                            EOF
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Terraform pipeline complete'
        }
    }
}
