- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: nginx-exporter-prometheus-nginx-exporter
    namespace: monitoring
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: nginx-exporter
      app.kubernetes.io/name: prometheus-nginx-exporter
      release: prometheus
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    jobLabel: nginx-exporter-prometheus-nginx-exporter
    selector:
      matchLabels:
        app.kubernetes.io/instance: nginx-exporter
        app.kubernetes.io/name: prometheus-nginx-exporter
