apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter-servicemonitor
  namespace: monitoring  # or default, depending on where you placed your exporter service
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx-exporter  # Ensure this matches the label on the Nginx exporter service
  endpoints:
    - port: metrics        # Ensure this matches the exporter’s metrics port in the service
      path: /metrics       # Adjust if necessary for specific exporters
      interval: 30s
