- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: redis-exporter-prometheus-redis-exporter
    namespace: monitoring
    labels:
      app.kubernetes.io/managed-by: Helm
      release: prometheus
  spec:
    endpoints:
    - port: redis-exporter
    jobLabel: redis-exporter-prometheus-redis-exporter
    namespaceSelector:
      matchNames:
      - monitoring
    selector:
      matchLabels:
        app.kubernetes.io/instance: redis-exporter
        app.kubernetes.io/name: prometheus-redis-exporter
