{
 "title": "Django",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Latency Including Middleware",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Body Size Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_responses_body_total_bytes_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency by View and Method",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[1m])) by (le, view, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}