{
 "title": "redis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total[1m])  *  100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "redis-up",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  }
 ]
}